/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_app_vision_MainActivity */

#ifndef _Included_com_app_vision_MainActivity
#define _Included_com_app_vision_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app_vision_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jintArray JNICALL Java_com_app_vision_MainActivity_text(JNIEnv *env, jobject instance, jlong addrGray);


#ifdef __cplusplus
}
#endif
#endif
